import os
import sys
import markdown
from pathlib import Path

def create_styled_html(md_path, html_path):
    """
    Converts a Markdown file to a beautifully styled HTML document.
    Includes Sky-Group branding and professional layout.
    """
    try:
        md_content = Path(md_path).read_text(encoding='utf-8')
        
        # Extensions for tables and code blocks
        html_body = markdown.markdown(md_content, extensions=['tables', 'fenced_code', 'toc'])
        
        # Professional CSS Template
        css = """
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;700&display=swap');
            body {
                font-family: 'Noto Sans KR', sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 900px;
                margin: 0 auto;
                padding: 40px;
                background-color: #f9f9f9;
            }
            .container {
                background: white;
                padding: 50px;
                border-radius: 8px;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            }
            h1, h2, h3 { color: #1a4f8b; border-bottom: 2px solid #eee; padding-bottom: 10px; }
            table { 
                width: 100%; 
                border-collapse: collapse; 
                margin: 20px 0; 
                background: #fff;
            }
            th, td { 
                border: 1px solid #ddd; 
                padding: 12px; 
                text-align: left; 
            }
            th { 
                background-color: #f2f6fa; 
                font-weight: bold; 
            }
            tr:nth-child(even) { background-color: #fcfcfc; }
            code { 
                background-color: #f4f4f4; 
                padding: 2px 5px; 
                border-radius: 4px; 
                font-family: Consolas, monospace;
            }
            pre { 
                background-color: #2d2d2d; 
                color: #ccc; 
                padding: 15px; 
                border-radius: 5px; 
                overflow-x: auto; 
            }
            .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #1a4f8b; }
            .footer { margin-top: 50px; font-size: 0.8em; color: #888; text-align: center; }
        </style>
        """
        
        full_html = f"""
        <!DOCTYPE html>
        <html lang="ko">
        <head>
            <meta charset="UTF-8">
            <title>Sky-Group Report: {Path(md_path).stem}</title>
            {css}
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>SKY-GROUP STRATEGY REPORT</h1>
                    <p>Intelligence System: Antigravity / Agent: Kkoma</p>
                </div>
                {html_body}
                <div class="footer">
                    &copy; 2026 Sky-Group All Rights Reserved. | Generated by OpenClaw AI
                </div>
            </div>
        </body>
        </html>
        """
        
        Path(html_path).write_text(full_html, encoding='utf-8')
        print(f"SUCCESS|{html_path}")
        
    except Exception as e:
        print(f"ERROR|{str(e)}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        # Default for the specific US Beauty report
        src = r"E:\Mywork\AI\AI컨텐츠제작\글로벌 AI 콘텐츠 플랫폼 마케팅 및 미국 상장 전략.md"
        dst = r"C:\Users\JayPark1004\.openclaw\workspace\US_Beauty_Report_styled.html"
    else:
        src = sys.argv[1]
        dst = src.replace('.md', '.html')
        
    create_styled_html(src, dst)
